baltechbook/baltechbook/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from corec import views as corviews
from corec.views import error_403, error_404, error_500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('accounts/', include('django.contrib.auth.urls')),
    url('', include('accounts.urls')), 
    url('', include('corec.urls')),
    url('', include('customer.urls')),
    url('', include('dev.urls')),
    url('', include('invoice.urls')),
    url('', include('order.urls')),
    url('', include('organizations.urls')),
    url('', include('stock.urls')),
]

handler403 = corviews.error_403 
handler404 = corviews.error_404
handler500 = corviews.error_500

baltechbook/dev/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
]

baltechbook/invoice/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'invoice/$', views.invoice, name='invoice'),
    url(r'invoice/add/$', views.orderInitDetails, name='orderDetails'),
    url(r'invoice/add/selectProducts/(?P<id>\d+)/', views.select_products_for_order, name='product-order'),
    url(r'invoice/add/selectCustomer/(?P<id>\d+)/', views.accept_customer_record, name='customer-records'),
    url(r'invoice/add/customer/(?P<id>\d+)/address/(?P<cust_id>\d+)/$', views.accept_customer_address, name='customer-address'),
    url(r'invoice/add/payment/(?P<id>\d+)/', views.payment, name='order-payment'),
    url(r'invoice/add/finalInvoice/(?P<id>\d+)/', views.generate_invoice, name='final-invoice'),

    # Delete Views
    url(r'invoice/(?P<po_id>\d+)/delete/', views.delete_product_order, name='product_order_delete'),
]

baltechbook/invoice/models.py
from __future__ import unicode_literals
from django.db import models

baltechbook/order/models.py
from __future__ import unicode_literals
from django.db import models
from organizations.models import organization_table
from customer.models import customer_address_table, customer_table
from accounts.models import employee_table
from stock.models import products_table

# Constants
from invoice.constants import MODE_OF_PAYMENT, ORDER_STATUS

# Order 
class order_table(models.Model):
    order_id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(customer_table, blank=True, null=True)
    organization_id = models.ForeignKey(organization_table, null=True, blank=True, default="")
    customer_address_id = models.ForeignKey(customer_address_table, null=True, blank=True, default="") # Billing/Shipping address
    employee_id = models.ForeignKey(employee_table, null=True, blank=True, default="")
    order_number = models.CharField(max_length=11)
    creation_date = models.DateField(auto_now=True)
    creation_time = models.TimeField(auto_now=True, null=True)
    status = models.CharField(max_length=11, null=True, default="", choices=ORDER_STATUS)

    def __unicode__(self):
        val = str(self.order_id)
        return val

    def __str__(self):
        val = str(self.order_id)
        return val

    class Meta:
        verbose_name = "Order"
        verbose_name_plural = "Orders"


# Product orders
class product_order_table(models.Model):
    product_order_id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(order_table)
    product_id = models.ForeignKey(products_table)
    product_price = models.IntegerField()
    quantity = models.IntegerField()
    post_tax_amount = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    delivery_date = models.DateField(default="", null=True, blank=True)

    def save(self, prod_name, quant, ind_prod_value, *args, **kwargs):
        to_read = products_table.objects.values_list('post_tax_price', flat=True).get(name=prod_name)
        value = ind_prod_value
        cgst = products_table.objects.values_list('cgst_tax', flat=True).get(name=prod_name)
        sgst = products_table.objects.values_list('sgst_tax', flat=True).get(name=prod_name)
        igst = products_table.objects.values_list('igst_tax', flat=True).get(name=prod_name)
        cgst_proportion = cgst/100 
        sgst_proportion = sgst/100
        igst_proportion = igst/100
        cgst_value = value * cgst_proportion
        sgst_value = value * sgst_proportion
        igst_value = value * igst_proportion
        final_value = value + cgst_value + sgst_value + igst_value
        self.post_tax_amount = final_value * quant
        super(product_order_table, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.product_order_id)

    def __unicode__(self):
        return unicode(str(self.product_order_id))

    class Meta:
        verbose_name = "Product Order"
        verbose_name_plural = "Product Orders"

# Payment
class payment_table(models.Model):
    payment_id = models.IntegerField(primary_key=True)
    order_id = models.ForeignKey(order_table)
    actual_amount = models.DecimalField(max_digits=15, decimal_places=2)
    discount = models.IntegerField()
    payable_amount = models.DecimalField(max_digits=15, decimal_places=2)
    mode_of_payment = models.CharField(max_length=10, choices=MODE_OF_PAYMENT, default="Cash")

    class Meta: 
        verbose_name = "Checkout"
        verbose_name_plural = "Checkout"

# Order Delivery Records
class delivery_record_table(models.Model):
    delivery_record_id = models.IntegerField(primary_key=True)
    order_id = models.ForeignKey(order_table)
    delivery_date = models.DateField()
    actual_delivery_date = models.DateField()

    class Meta:
        verbose_name = "Delivery Record"
        verbose_name_plural = "Delivery Records"

baltechbook/customer/forms.py
from django import forms
from .models import customer_table, customer_address_table

class CustomerBasicDetailForm(forms.ModelForm):
    class Meta:
        model = customer_table
        fields = {'name', 'mobileNumber', 'email'}

        labels = {
            'name': "Customer's Name",
            'email': "Customer's Email Address",
            'mobileNumber': "Customer's Mobile Number"
        }

    def __init__(self, *args, **kwargs):
        super(CustomerBasicDetailForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ExistingCustomerDetailForm(forms.Form):
    customer_info = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(ExistingCustomerDetailForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['readonly'] = True
            visible.field.widget.attrs['placeholder']  = "Select a Customer from below list and if found, click on the name and then press 'Found the Customer' button"

# ----------------
# Customer Address

class NewCustomerAddressForm(forms.ModelForm):
    class Meta:
        model = customer_address_table
        fields = {'address', 'city', 'state', 'country', 'pincode', 'phoneNumber', 'email', 'address_type', 'customer_id'}

        widgets = {
            'customer_id': forms.TextInput(attrs={'readonly': True}),
            'phoneNumber': forms.TextInput(attrs={'required': False}),
            'email': forms.TextInput(attrs={'required': False})
        }

        labels = {
                'phoneNumber': 'Alternate Mobile Number',
                'email': 'Alternate Email Address',
        }

    def __init__(self, *args, **kwargs):
        super(NewCustomerAddressForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ExistingCustomerAddressForm(forms.Form):
    customer_address = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(ExistingCustomerAddressForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['readonly'] = True
            visible.field.widget.attrs['placeholder']  = "Select a Customer Address from below list and if found, click on the address and then press 'Proceed to Payment' button" 

baltechbook/invoice/forms.py
from django import forms
from django.forms import ModelForm
from order.models import *


class order_init_details(forms.ModelForm):
    class Meta:
        model = order_table
        fields = {'order_number', 'organization_id'}
        widgets = {
            'order_number': forms.TextInput(attrs={'class': "form-control", 'readonly': True}),
            'organization_id': forms.TextInput(attrs={'class': "form-control", 'readonly': True}),
        }

baltechbook/order/forms.py
from django import forms
from .models import *
from stock.models import products_table
from invoice.constants import *

# Changing default input format to date input
class DateInput(forms.DateInput):
    input_type = 'date'

class ProductsOrderForm(forms.ModelForm):
    class Meta:
        model = product_order_table
        fields = {'order_id', 'product_id', 'quantity', 'delivery_date', 'product_price'}

        widgets = {
            'order_id': forms.TextInput(attrs={'readonly': True}),
            'delivery_date': DateInput()
        }

        labels = {
            'product_id': 'Select a Product',
            'quantity': 'Enter Supply Quantity',
            'product_price': 'Enter Product Price',
            'delivery_date': 'Enter Delivery Date',
            'order_id': 'Order ID'
        }



    def __init__(self, *args, **kwargs):
        super(ProductsOrderForm, self).__init__(*args, **kwargs)
        self.fields['product_id'].queryset = products_table.objects.all()
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'delivery_date':
                field.widget.attrs['placeholder'] = 'Enter in the following format YYYY-MM-DD'
            elif field_name == 'quantity':
                field.widget.attrs['placeholder'] = 'Enter a number'


# Payment form
class PaymentForm(forms.ModelForm):
    sales_executive = forms.ModelChoiceField(employee_table.objects.none(), required=False)

    class Meta:
        model = payment_table
        fields = {'order_id', 'actual_amount', 'discount', 'payable_amount', 'mode_of_payment'}

        widgets = {
            'order_id': forms.Select(attrs={'readonly': True}),
            'actual_amount': forms.TextInput(attrs={'readonly': True}),
            'payable_amount': forms.TextInput(attrs={'readonly': True})
        }

        labels = {
            'employee_id': 'Reference',
        }

    def __init__(self, *args, **kwargs):
        super(PaymentForm, self).__init__(*args, **kwargs)
        self.fields['sales_executive'].queryset = employee_table.objects.filter(employee_type="Sales Executive")
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        return super(PaymentForm, self).save(commit=commit)

baltechbook/invoice/templates/customer-address-record.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	{% include 'reqs/headerBar.html' %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/customer-record.css' %}">

	<style type="text/css">
		.disable {
			color: currentColor;
			cursor: not-allowed;
			opacity: 0.5;
			text-decoration: none;
			pointer-events: none;
		}
	</style>
</head>

<body>
	{% if user.admin %}
		{% include 'reqs/navbar.html' %}
	{% else %}
		{% include 'reqs/se_navbar.html' %}
	{% endif %}

	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<!-- New Invoice Begins -->
		<nav class="navbar navbar-light bg-light">
		  <a class="navbar-brand">
		    <i class="fas fa-file-invoice"></i>
		  </a>
		  <!-- Add Items to Cart -->
		  <a class="navbar-brand">
		  	<i class="fas fa-long-arrow-alt-right"></i>
		    <i class="fas fa-cart-plus"></i>
		  </a>
		  <!-- Customer Personal Info -->
		  <a class="navbar-brand">
		  	<i class="fas fa-long-arrow-alt-right"></i>
		    <i class="fas fa-user-lock"></i>
		  </a>
		  <!-- Customer Location Info -->
		  <a class="navbar-brand">
		  	<i class="fas fa-long-arrow-alt-right"></i>
		    <i class="fas fa-map-marked-alt"></i>
		  </a>
		  <!-- Checkout -->
		  <a class="navbar-brand disable">
		  	<i class="fas fa-long-arrow-alt-right"></i>
		    <i class="fas fa-cash-register"></i>
		  </a> 	
		</nav>

		<div class="row">
			<div class="col-lg-12">
				<h2>Customer Information</h2>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<h2>Add A New Address</h2>
				<hr>
				<form method="POST" name="" id="">
					{% csrf_token %}
					<legend>Customer Address</legend>
					<div class="form-group col-md-6">
						<label>{{ form_new.address.label_tag }}</label>
						{{ form_new.address }}
						{{ form_new.address.errors }}
					</div>
					<div class="form-group col-md-6">
						<label>{{ form_new.city.label_tag }}</label>
						{{ form_new.city }}
						{{ form_new.city.errors }}
					</div>
					<div class="form-group col-md-6">
						<label>{{ form_new.state.label_tag }}</label>
						{{ form_new.state }}
						{{ form_new.state.errors }}
					</div>
					<div class="form-group col-md-6">
						<label>{{ form_new.country.label_tag }}</label>
						{{ form_new.country }}
						{{ form_new.country.errors }}
					</div>
					<div class="form-group col-md-6">
						<label>{{ form_new.pincode.label_tag }}</label>
						{{ form_new.pincode }}
						{{ form_new.pincode.errors }}
					</div>
					<div class="form-group col-md-6">
						<label>{{ form_new.address_type.label_tag }}</label>
						{{ form_new.address_type }}
						{{ form_new.address_type.errors }}
					</div>
					<div class="form-group col-md-6"></div>
					<legend>Alternate Contact Information</legend>
					<div class="form-group col-md-6">
						<label>{{ form_new.phoneNumber.label_tag }}</label>
						{{ form_new.phoneNumber }}
						{{ form_new.phoneNumber.errors }}
					</div>
					<div class="form-group col-md-6">
						<label>{{ form_new.email.label_tag }}</label>
						{{ form_new.email }}
						{{ form_new.email.errors }}
					</div>
					<legend>Customer Information</legend>
					<div class="form-group col-md-6">
						<label>{{ form_new.customer_id.label_tag }}</label>
						{{ form_new.customer_id }}
						{{ form_new.customer_id.errors }}
					</div>
					<div class="form-group col-md-12">
						<button class="btn btn-default btn-md btn-success" value="submit">
							Selected Address...Move to Payments <i class="fas fa-money-check-alt"></i>
						</button>
					</div>
					<hr>
				</form>	 
			</div>
		</div>

		<div class="text-center" style="font-size: 20px;">
			<legend>OR</legend>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<h2>Existing Addresses of this Customer</h2>
				<form method="POST" id="existing_customer_address" name="existing_customer_address">
					{% csrf_token %}
					{% for field in form_existing %}
						<label>{{ field.label_tag }}</label>
						{{ field }}
						{{ field.errors }}
					{% endfor %}<br>
					<button class="btn btn-default btn-md btn-success" value="submit">
						Proceed to Payment <i class="fas fa-money-check-alt"></i>
					</button><br><br>
					<div class="list-group">
						<ul id="existing_addresses_list">
							{% for object in address_list %}
							<li data-value="{{ object.customer_address_id }}">
								<a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
									<div class="d-flex w-100 justify-content-between">
										<h5 class="mb-1">{{ object.city }}, {{ object.state }}, {{ object.country }}</h5>
									</div>
									<p class="mb-1">{{ object.address }} - {{ object.pincode }}</p>
									<small>{{ object.address_type }}</small>
							  	</a>
							  </li>
						  	{% endfor %}
					  	</ul>
					</div>
				</form>
			</div>
		</div>	
	</div>

{% include 'reqs/footerScripts.html' %}

	<!-- Fetching value from list to input area for form -->
	<script>
		$("#existing_addresses_list").on("click", "a", function(e){
		    e.preventDefault();
		    var $this = $(this).parent();
		    $this.addClass("select").siblings().removeClass("select");
		    $("#id_customer_address").val($this.data("value"));
		});

		$("form[name=existing_customer_address]").submit(function(e) {
		    if ($(this).find("li.select").length == 0) {
		        alert( "Please select an address...or add a New One!" );
		        e.preventDefault();
		    }
		});
	</script>

</body>
</html>

baltechbook/invoice/templates/initialOrderDetails.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	{% include 'reqs/headerBar.html' %}
	<style type="text/css">
		.disable {
			color: currentColor;
			cursor: not-allowed;
			opacity: 0.5;
			text-decoration: none;
			pointer-events: none;
		}
	</style>
</head>

<body>
	{% if user.admin %}
		{% include 'reqs/navbar.html' %}
	{% else %}
		{% include 'reqs/se_navbar.html' %}
	{% endif %}

	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<!-- New Invoice Begins -->
		<nav class="navbar navbar-light bg-light">
		  <a class="navbar-brand">
		    <i class="fas fa-file-invoice"></i>
		  </a>
		  <!-- Add Items to Cart -->
		  <a class="navbar-brand disable">
		  	<i class="fas fa-long-arrow-alt-right"></i>
		    <i class="fas fa-cart-plus"></i>
		  </a>
		  <!-- Customer Personal Info -->
		  <a class="navbar-brand disable">
		  	<i class="fas fa-long-arrow-alt-right"></i>
		    <i class="fas fa-user-lock"></i>
		  </a>
		  <!-- Customer Location Info -->
		  <a class="navbar-brand disable">
		  	<i class="fas fa-long-arrow-alt-right"></i>
		    <i class="fas fa-map-marked-alt"></i>
		  </a>
		  <!-- Checkout -->
		  <a class="navbar-brand disable">
		  	<i class="fas fa-long-arrow-alt-right"></i>
		    <i class="fas fa-cash-register"></i>
		  </a> 	
		</nav>

		<div class="row">
			<div class="col-lg-12">
				<h2>New Invoice Details</h2>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<form class="form-horizontal" action="" method="POST">
					{% csrf_token %}
					<legend>Order Details</legend>
					<div class="form-group">
						<label class="col-md-3 control-label" for="name">{{ form.order_number.label_tag }}</label>
						<div class="col-md-9">
							{{ form.order_number }}
							{{ form.order_number.errors }}
						</div>
					</div>
					<legend>Organization Info</legend>
					<div class="form-group">
						<label class="col-md-3 control-label" for="name">{{ form.organization_id.label_tag }}</label>
						<div class="col-md-9">
							{{ form.organization_id }}
							{{ form.organization_id.errors }}
						</div>
					</div>
					<hr>
					<div class="form-group">
						<div class="col-md-12">
							<button type="submit" class="btn btn-default btn-md pull-right btn-primary btn-success">
								Proceed to Selecting Products
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>

{% include 'reqs/footerScripts.html' %}

</body>
</html>

baltechbook/invoice/templates/orderPayment.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    {% include 'reqs/headerBar.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/customer-record.css' %}">

    <style type="text/css">
        .disable {
            color: currentColor;
            cursor: not-allowed;
            opacity: 0.5;
            text-decoration: none;
            pointer-events: none;
        }
    </style>
</head>

<body>
    {% if user.admin %}
        {% include 'reqs/navbar.html' %}
    {% else %}
        {% include 'reqs/se_navbar.html' %}
    {% endif %}

    <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
        <!-- New Invoice Begins -->
        <nav class="navbar navbar-light bg-light">
          <a class="navbar-brand">
            <i class="fas fa-file-invoice"></i>
          </a>
          <!-- Add Items to Cart -->
          <a class="navbar-brand">
            <i class="fas fa-long-arrow-alt-right"></i>
            <i class="fas fa-cart-plus"></i>
          </a>
          <!-- Customer Personal Info -->
          <a class="navbar-brand">
            <i class="fas fa-long-arrow-alt-right"></i>
            <i class="fas fa-user-lock"></i>
          </a>
          <!-- Customer Location Info -->
          <a class="navbar-brand">
            <i class="fas fa-long-arrow-alt-right"></i>
            <i class="fas fa-map-marked-alt"></i>
          </a>
          <!-- Checkout -->
          <a class="navbar-brand">
            <i class="fas fa-long-arrow-alt-right"></i>
            <i class="fas fa-cash-register"></i>
          </a>  
        </nav>


        <div class="row">
            <div class="col-lg-12">
                <h2>Checkout Review</h2>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <h2>Payment</h2>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group col-md-6">
                        <label>{{ payment_form.order_id.label_tag }}</label>
                        {{ payment_form.order_id }}
                        {{ payment_form.order_id.errors }}
                    </div>
                    <legend>Actual Transaction</legend>
                    <div class="form-group col-md-6">
                        <label>{{ payment_form.actual_amount.label_tag }}</label>
                        {{ payment_form.actual_amount }}
                        {{ payment_form.actual_amount.errors }}
                    </div>
                    <div class="form-group col-md-6">
                        <label>{{ payment_form.discount.label_tag }}</label>
                        {{ payment_form.discount }}
                        {{ payment_form.discount.errors }}
                    </div>
                    <legend>Final Transaction</legend>
                    <div class="form-group col-md-6">
                        <label>{{ payment_form.payable_amount.label_tag }}</label>
                        {{ payment_form.payable_amount }}
                        {{ payment_form.payable_amount.errors }}
                    </div>
                    <div class="form-group col-md-6">
                        <label>{{ payment_form.mode_of_payment.label_tag }}</label>
                        {{ payment_form.mode_of_payment }}
                        {{ payment_form.mode_of_payment.errors }}
                    </div>

                    <!-- For admin vs For sales_executive -->
                    {% if user.admin == True %}
                        <!-- For admin -->
                        <div class="form-group col-md-6">
                            <label>{{ payment_form.sales_executive.label_tag }}</label>
                            {{ payment_form.sales_executive }}
                            {{ payment_form.sales_executive.errors }}
                        </div>
                        <!-- /For admin -->
                    {% endif %}
                    {% if user.admin == False %}
                        <!-- For Sales executive -->
                        <div class="form-group col-md-6">
                            <label>{{ payment_form.sales_executive.label_tag }}</label>
                            <input type="text" name="sales_executive" value="{{ user.id }}" readonly required class="form-control" id="id_sales_executive" />
                            {{ payment_form.sales_executive.errors }}
                        </div>
                        <!-- /For Sales executive -->
                    {% endif %}

                    <div class="form-group col-md-12">
                        <button class="btn btn-default btn-md btn-success" value="submit">
                            Generate Invoice <i class="fas fa-file-invoice"></i>
                        </button>
                    </div>
                    <hr>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <h2>Products</h2>
                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Product Name</th>
                        <th>Actual Price</th>
                        <th>CGST</th>
                        <th>SGST</th>
                        <th>IGST</th>
                        <th>Quantity</th>
                        <th>Post Tax Amount</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for object1 in all_products %}
                            <tr>
                                <td>{{ object1.product_id }}</td>
                                <td>{{ object1.product_id.actual_price }}</td>
                                <td>{{ object1.product_id.cgst_tax }}</td>
                                <td>{{ object1.product_id.sgst_tax }}</td>
                                <td>{{ object1.product_id.igst_tax }}</td>
                                <td>{{ object1.quantity }}</td>
                                <td>{{ object1.product_price }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <hr>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <h2>Customer Information</h2>
                <hr>
                <!-- {{ customer_info }}
                {{ customer_address }} -->

                
                <table class="table table-bordered">
                    <tr>
                      <th>Name</th>
                      <td>{{ customer_info.name }}</td>
                    </tr>
                    <tr>
                      <th>Email</th>
                      <td>{{ customer_info.email }}</td>
                    </tr>
                    <tr>
                      <th>Mobile Number</th>
                      <td>{{ customer_info.mobileNumber }}</td>
                    </tr>
                    <tr>
                      <th>Billing/Shipping Address</th>
                      <td>{{ customer_address.address }}, {{ customer_address.city }} - {{ customer_address.pincode }}</td>
                    </tr>
                    <tr>
                      <th>State</th>
                      <td>{{ customer_address.state }}</td>
                    </tr>
                    <tr>
                      <th>Country</th>
                      <td>{{ customer_address.country }}</td>
                    </tr>
                    <tr>
                        <th>Alternate Email</th>
                        {% if customer_address.email == None %}
                            <td> - </td>
                        {% else %}
                            <td>{{ customer_address.email }}</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <th>Alternate Mobile Number</th>
                        {% if customer_address.phoneNumber == '' %}
                            <td> - </td>
                        {% else %}
                            <td>{{ customer_address.phoneNumber }}</td>
                        {% endif %}
                    </tr>
                    <tr>
                      <th>Date of issuing</th>
                      <td>{{ order_record.creation_date }}, {{order_record.creation_time }}</td>
                    </tr>
                </table>
            </div>
        </div>

    </div>

{% include 'reqs/footerScripts.html' %}

    <!-- Fetching value from list to input area for form -->
    <script>
        $("#existing_addresses_list").on("click", "a", function(e){
            e.preventDefault();
            var $this = $(this).parent();
            $this.addClass("select").siblings().removeClass("select");
            $("#id_customer_address").val($this.data("value"));
        });

        $("form[name=existing_customer_address]").submit(function(e) {
            if ($(this).find("li.select").length == 0) {
                alert( "Please select an address...or add a New One!" );
                e.preventDefault();
            }
        });
    </script>

    <!-- JQeury func to automatically change final amount field value, based on discount selection -->
    <script type="text/javascript">
        $(document).ready(function()
        {
            function updatePrice()
            {
                var price = parseFloat($("#id_discount").val());
                var actual_amount = parseFloat($("#id_actual_amount").val());
                var total = actual_amount - price;
                var total = total.toFixed(2);
                $("#id_payable_amount").val(total);
            }
            $(document).on("change, keyup", "#id_discount", updatePrice);
        });
    </script>

</body>
</html>